export { default as CheckCircle } from './CheckCircle'
export { default as Logo } from './Logo'
export { default as LogoGetir } from './LogoGetir'
export { default as Plus } from './Plus'
export { default as Wastebasket } from './Wastebasket'